### ISSUE TITLE
RFE: Linux standalone could use jack as well as alsa.

### ISSUE THREAD

**Issue by Baggypants** [augustofilocamo/superOrgan#1]
Jack is a low latency audio interconnect and driver for Linux. It would be helpful for the standalone version. We can use the vst ver in the meantime.

**Comment by davidhealey** [comment]
That's weird, JACK should be available, but you're right it's not showing up. I'll investigate.

**Comment by davidhealey** [comment]
Ok I found the issue, making a new build now.

**Comment by davidhealey** [comment]
I've replaced the installer in the v1.0.0 release. Should have JACK support now, please test and report back.

**Comment by Baggypants** [comment]
I've downloaded it again from https://sampleson.com/collab3-thanks.html but Jack doesn't show up in the Driver drop down, only Alsa. It's a bit tricky to confirm which version I have. :)

**Comment by davidhealey** [comment]
Download from here - https://github.com/augustofilocamo/superOrgan/releases

**Comment by Baggypants** [comment]
That's the one. Works with Jack now, ace job.

**Comment by jofemodo** [comment]
But ... where is the source code?

**Comment by davidhealey** [comment]
Click the button that says Code :p

![image](https://user-images.githubusercontent.com/14021202/79057799-52223e00-7c5d-11ea-8851-9bf90296f1c2.png)

You'll also need [HISE](https://github.com/christophhart/HISE)

**Comment by jofemodo** [comment]
Is this code the main program?

https://github.com/augustofilocamo/superOrgan/blob/master/Scripts/ScriptProcessors/CollaB3/ScriptProcessorMain.js

Can you explain a little bit about the audio engine?

**Comment by davidhealey** [comment]
@jofemodo The instrument is created with HISE, a tool for building virtual instruments. HISE provides the audio engine which we have used to create CollaB3. This repo contains our HISE project, it doesn't contain the HISE audio engine.

HISE allows us to control and interact with its audio engine using scripting (similar to JavaScript). That is what you've found in the Scripts folder.

**Comment by jofemodo** [comment]
OK! I understand ...
